parameters:
  thrift.client.class: Overblog\ThriftBundle\Client\ThriftClient
  thrift.client.test.class: Overblog\ThriftBundle\Client\ThriftTestClient
  thrift.compile_warmer.class: Overblog\ThriftBundle\CacheWarmer\ThriftCompileCacheWarmer
  thrift.factory.class: Overblog\ThriftBundle\Factory\ThriftFactory
  thrift.classloader.listener.class: Overblog\ThriftBundle\Listener\ClassLoaderListener
  thrift.cache_dir: '%kernel.cache_dir%'
  thrift.use_composer_loader: false

services:
  thrift.compile_warmer:
    class: %thrift.compile_warmer.class%
    arguments: ['%kernel.cache_dir%', %kernel.root_dir%, %thrift.config.compiler.path%, %thrift.config.services%]

  thrift.factory:
    class: %thrift.factory.class%
    arguments: [%thrift.config.services%]

  thrift.routing.loader:
    class: Overblog\ThriftBundle\Routing\ThriftRoutingLoader
    arguments: [%thrift.config.servers%]
    tags:
      - { name: routing.loader, priority: 255 }
